/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTD3 (number 60), RESET
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RESET_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RESET_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RESET_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RESET_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RESET_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD2 (number 59), X_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_X_INT_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_X_INT_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_X_INT_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_X_INT_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_X_INT_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
